<?php
// $Id$

/**
 * hook_image_default_styles() {
 */
function features_rgallery_image_default_styles() {
  $styles = array();

  $styles['rgallery_cover'] = array(
    'effects' => array(
      array(
        'name' => 'image_scale_and_crop',
        'data' => array('width' => 144, 'height' => 144),
        'weight' => 0,
      ),
    ),
  );
  $styles['rgallery_thumbnail'] = array(
    'effects' => array(
      array(
        'name' => 'image_scale',
        'data' => array('width' => 128, 'height' => 128),
        'weight' => 0,
      ),
    ),
  );
  $styles['rgallery_full_view'] = array(
    'effects' => array(
      array(
        'name' => 'image_scale',
        'data' => array('width' => 600, 'height' => 512),
        'weight' => 0,
      ),
    ),
  );

  return $styles;
}

/**
 * Implements hook_sf_default_variables().
 */
function features_rgallery_sf_default_variables() {
  return array(
    'rgallery_imagestyle_preview' => 'rgallery_full_view',
    'rgallery_imagestyle_thumbnail' => 'rgallery_thumbnail',
    'rgallery_imagestyle_cover' => 'rgallery_cover',
  );
}

/**
 * Implements hook_sf_default_permissions().
 */
function features_rgallery_sf_default_permissions() {
  return array(
    'administrator' => array(
      'create ralbum content' => 1,
      'edit own ralbum content' => 1,
      'edit any ralbum content' => 1,
      'delete own ralbum content' => 1,
      'delete any ralbum content' => 1,
      'create rphoto content' => 1,
      'edit own rphoto content' => 1,
      'edit any rphoto content' => 1,
      'delete own rphoto content' => 1,
      'delete any rphoto content' => 1,
      'view any gallery' => 1,
      'manage rgallery' => 1,
      'administer rgallery' => 1,
    ),
  );
}

/**
 * Implements hook_sf_sample_contents().
 */
function features_rgallery_sf_sample_contents() {
  // Album
  /*$album = new stdClass();
  $album->type = 'ralbum';
  $album->title = t('Example Album');
  $album->privacy = 1;
  $album->uid = 1;
  node_save($album);
  $nodes[] = (array)$album;
  // Photo
  $filepath = drupal_get_path('module', 'features_rgallery') .'/rutcreate.png';
  $filename = basename($filepath);
  $source = new stdClass();
  $source->uri = $filepath;
  $source->uid = 1;
  $source->filemime = file_get_mimetype(trim(basename($filename), '.'));
  if ($file = file_copy($source, 'public://', FILE_EXISTS_RENAME)) {
    $photo = new stdClass();
    $photo->title = $file->filename;
    $photo->type = 'rphoto';
    $photo->body[LANGUAGE_NONE][0] = array(
      'value' => $file->filename,
      'format' => 1,
    );
    $photo->uid = $GLOBALS['user']->uid;
    $photo->name = $GLOBALS['user']->name;
    $photo->status = 1;
    $photo->promote = 0;
    if (module_exists('comment')) {
      $photo->comment = variable_get('comment_'. $photo->type, COMMENT_NODE_OPEN);
    }
    node_save($photo);
    if ($photo->nid) {
      $last_weight = db_query("SELECT weight FROM {ralbum} WHERE aid = :aid ORDER BY weight DESC", array(':aid' => $album->nid))->fetchCol();
      $weight = 0;
      if (!empty($last_weight)) $weight = $last_weight[0] + 1;
      $is_thumbnail = ($weight == 0) ? 1 : 0;
      db_insert('ralbum')
        ->fields(array(
          'aid' => $album->nid,
          'pid' => $photo->nid,
          'fid' => $file->fid,
          'weight' => $weight,
          'is_thumbnail' => $is_thumbnail
        ))
        ->execute();
      $nodes[] = (array)$photo;
      return $nodes;
    }
  }*/
  return array();
}
