<?php
// $Id$

/**
 * @file
 */

/**
 * Implement hook_permission().
 */
function sfpackage_permission() {
  return array(
    'select package' => array(
      'title' => 'Select package',
      'description' => 'Select package with simple feature.',
    ),
  );
}

/**
 * Implements hook_menu().
 */
function sfpackage_menu() {
  $items['admin/packages'] = array(
    'title' => t('Select package'),
    'page callback' => 'sfpackage_select',
    'access arguments' => array('select package'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function sfpackage_theme($existing, $type, $theme, $path) {
  return array(
    'sfpackage_select' => array(
      'variables' => array('packages' => NULL),
      'file' => 'sfpackage.tpl.php',
    ),
  );
}

function sfpackage_select() {
  $packages = Package::getInfoAll();
  foreach($packages as $package) {
    $content = '<div>';
    $content .= '<a title="'.$package->name.'" href="/admin/package?select='.$package->code.'">';
    $content .= theme('image', array(
      'path' => $package->thumbnail, 
      'alt' => $package->name, 
      'title' => $package->description,
    ));
    $content .= '</a>';
    $content .= '<div class="package-layer"><div class="package-name">'.$package->name.'</div></div>';
    $content .= '</div>';

    $contents[] = $content;
  }

  drupal_add_css(drupal_get_path('module', 'sfpackage').'/sfpackage.css');
  drupal_add_js(drupal_get_path('module', 'sfpackage').'/sfpackage.js');
  return theme('item_list', array(
    'items' => $contents,
    'attributes' => array(
      'class' => 'package-select',
    ),
  ));

}


